apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener-server
  template:
    metadata:
      labels:
        app: url-shortener-server
    spec:
      containers:
        - name: server
          image: url-shortener-server
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 1
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 1
            failureThreshold: 5
            timeoutSeconds: 1
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 1
            failureThreshold: 30
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-server
spec:
  type: ClusterIP
  selector:
    app: url-shortener-server
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: url-shortener-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: url-shortener-server
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

